# Generated by Django 4.2 on 2025-01-22 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=20)),
                ('receiver_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('last_accessed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('location', 'Location'), ('template', 'Template'), ('sticker', 'Sticker'), ('video', 'Video'), ('interactive', 'Interactive')], max_length=20)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.BooleanField(default=False)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_language', models.CharField(blank=True, max_length=10, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whats_app.thread')),
            ],
        ),
    ]
