# Generated by Django 4.2 on 2025-01-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_app', '0002_message_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='preview_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='template_language',
        ),
        migrations.RemoveField(
            model_name='message',
            name='template_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image')], max_length=20),
        ),
    ]
